functional:
  - Пользователь должен иметь возможность зарегистрироватся
  - Пользователь должен иметь возможность войти на сайт под своим аккаунтом 
  - Пользователь должен иметь возможность участвовать в игре без регистрации 
  - Авторизованный пользователь может выбирать уровень сложности, тип игры, временные рамки и задачу в создаваемой игре
  - В игру можно играть с любым человеком, с ботом или с другом
  - Авторизованный пользователь имеет доступ к таблице 'Лидеров'
  - Авторизованный пользователь имеет доступ к лобби, к списку турниров и к списку завершённых игр
  - Авторизованный пользователь имеет доступ к записям завершённых игр
  - Состязание можно проводить на разных языках программирования 
  - Задачи решаются на скорость против другого игрока. 
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - Задачу можно переключать между двумя языками — русском и английском
  - Пользователь может подключиться к идущей игре, в качестве зрителя 
  - На основе полученных очков, формируется рейтинг за неделю, месяц и за все время для пользователя
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - требование 5
  - требование 6
