functional:
  - Пользователь должен иметь возможность зарегистрироватся
  - Пользователь должен иметь возможность войти на сайт под своим аккаунтом 
  - Пользователь должен иметь возможность участвовать в игре без регистрации 
  - Авторизованный пользователь может создавать игру
  - Авторизованный пользователь имеет доступ к таблице 'Лидеров'
  - Авторизованный пользователь имеет доступ к лобби, к списку турниров и к списку завершённых игр
  - 
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - требование 5
  - требование 6
